### ISSUE TITLE
rclone mount fails - /dev/fuse: Operation not permitted

### ISSUE THREAD

**Issue by erikbrodnick** [allfro/device-mapping-manager#2]
I am attempting to perform an rclone mount inside a docker swarm service container.

$ rclone -vv mount <remote>:<path> /mnt

mount helper error: fusermount: failed to open /dev/fuse: Operation not permitted
Fatal error: failed to mount FUSE fs: fusermount: exit status 1

In docker-compose.yml

```
version: '3.8'
services:
  service:
    image: <my/image>
    volumes:
      - dev_fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN

volumes:
  dev_fuse:
    driver: redcanari/device-volume-driver
    driver_opts:
      device: /dev/fuse
```

Any suggestions?
